import { Command } from "commander";
import fs from "node:fs";
import path from "node:path";
import {
	scanFoundryOut,
	scanHardhatArtifacts,
	type FoundryArtifact,
} from "../extract/foundryParser.js";
import type { SolidityErrorABI, SolidityErrorInput } from "../types.js";
import { writeShortStringCodesFromSolidity } from "../helpers/shortStringCodesGen.js";

const program = new Command();

function solidityTypeToTs(type: string): string {
	if (type.startsWith("uint") || type.startsWith("int")) return "bigint";
	if (type === "address") return "`0x${string}`";
	if (type === "bool") return "boolean";
	if (type === "string") return "string";
	if (type.startsWith("bytes")) return "`0x${string}`";
	if (type.endsWith("[]")) {
		const inner = type.slice(0, -2);
		return `readonly ${solidityTypeToTs(inner)}[]`;
	}
	return "unknown";
}

function generateInputType(inputs: SolidityErrorInput[]): string {
	if (inputs.length === 0) return "Record<string, never>";

	const fields = inputs.map((i) => {
		const name = i.name || "unnamed";
		if (i.components && i.components.length > 0) {
			return `    ${name}: { ${i.components.map((c) => `${c.name}: ${solidityTypeToTs(c.type)}`).join("; ")} }`;
		}
		return `    ${name}: ${solidityTypeToTs(i.type)}`;
	});

	return `{\n${fields.join(";\n")};\n  }`;
}

function generateTypes(errors: SolidityErrorABI[]): string {
	const seen = new Set<string>();
	const lines: string[] = [];

	lines.push("// Auto-generated by @abiregistry/error-decoder");
	lines.push("// Do not edit manually\n");

	for (const err of errors) {
		if (seen.has(err.name)) continue;
		seen.add(err.name);

		const argsType = generateInputType(err.inputs);

		lines.push(`export interface ${err.name}Error {`);
		lines.push(`  name: "${err.name}";`);
		lines.push(`  args: ${argsType};`);
		lines.push("}\n");
	}

	const allNames = [...seen].map((n) => `${n}Error`);
	lines.push(`export type SolidityCustomError = ${allNames.join(" | ")};\n`);

	return lines.join("\n");
}

function generateRegistry(errors: SolidityErrorABI[]): string {
	const seen = new Set<string>();
	const lines: string[] = [];

	lines.push("// Auto-generated by @abiregistry/error-decoder");
	lines.push("// Do not edit manually\n");
	lines.push('import type { Abi } from "viem";\n');

	lines.push("export const ERROR_ABI: Abi = [");
	for (const err of errors) {
		const sig = `${err.name}(${err.inputs.map((i) => i.type).join(",")})`;
		if (seen.has(sig)) continue;
		seen.add(sig);

		lines.push("  {");
		lines.push('    type: "error",');
		lines.push(`    name: "${err.name}",`);
		lines.push(`    inputs: ${JSON.stringify(err.inputs)},`);
		lines.push("  },");
	}
	lines.push("];\n");

	return lines.join("\n");
}

function generateContracts(
	artifacts: FoundryArtifact[],
	outDir: string,
	sourceDir: string,
): string[] {
	const generated: string[] = [];

	for (const artifact of artifacts) {
		const sourcePath = path.join(sourceDir, artifact.fileName);
		let fullJson: any;
		try {
			fullJson = JSON.parse(fs.readFileSync(sourcePath, "utf8"));
		} catch {
			continue;
		}

		const bytecode: string | undefined = fullJson?.bytecode?.object;
		const name = artifact.contractName;
		const lines: string[] = [];

		lines.push("// Auto-generated by @abiregistry/error-decoder");
		lines.push("// Do not edit manually\n");

		lines.push(
			`export const ${name}ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
		);

		if (bytecode) {
			lines.push(`export const ${name}Bytecode = "${bytecode}" as const;\n`);
		}

		const filePath = path.join(outDir, `${name}.ts`);
		fs.writeFileSync(filePath, lines.join("\n"), "utf8");
		generated.push(name);
	}

	return generated;
}

function generateBarrel(
	outDir: string,
	contractNames: string[],
	hasErrorTypes: boolean,
	hasErrorAbi: boolean,
): string {
	const lines: string[] = [];
	lines.push("// Auto-generated by @abiregistry/error-decoder");
	lines.push("// Do not edit manually\n");

	if (hasErrorTypes) lines.push('export * from "./errors.types.js";');
	if (hasErrorAbi) lines.push('export { ERROR_ABI } from "./errors.abi.js";');

	for (const name of contractNames) {
		lines.push(`export { ${name}ABI, ${name}Bytecode } from "./${name}.js";`);
	}

	// Client-generated short-string map (optional; see `generate-short-codes` command)
	const shortCodesPath = path.join(outDir, "shortStringCodes.ts");
	if (fs.existsSync(shortCodesPath)) {
		lines.push('export { SHORT_STRING_ERROR_CODES } from "./shortStringCodes.js";');
	}

	lines.push("");
	return lines.join("\n");
}

program
	.name("@abiregistry/error-decoder")
	.description(
		"Generate TypeScript types and ABI registry from Solidity build artifacts",
	)
	.version("0.1.0");

program
	.command("generate")
	.description("Generate TypeScript types and ABI from build artifacts")
	.option("-f, --foundry <path>", "Path to Foundry out/ directory", "./out")
	.option("-h, --hardhat <path>", "Path to Hardhat artifacts/ directory")
	.option(
		"-o, --output <dir>",
		"Output directory for generated files",
		"./generated",
	)
	.option("--types-only", "Only generate TypeScript types", false)
	.option("--abi-only", "Only generate ABI registry", false)
	.option(
		"--contracts",
		"Also generate per-contract ABI + bytecode files",
		false,
	)
	.action((opts) => {
		const allErrors: SolidityErrorABI[] = [];
		const allArtifacts: FoundryArtifact[] = [];
		let sourceDir = "";

		if (opts.foundry && fs.existsSync(path.resolve(opts.foundry))) {
			sourceDir = path.resolve(opts.foundry);
			console.log(`Scanning Foundry artifacts at ${opts.foundry}...`);
			const artifacts = scanFoundryOut(opts.foundry);
			allArtifacts.push(...artifacts);
			for (const a of artifacts) {
				allErrors.push(...a.errors);
			}
			console.log(`  Found ${artifacts.length} contracts with errors`);
		}

		if (opts.hardhat && fs.existsSync(path.resolve(opts.hardhat))) {
			sourceDir = sourceDir || path.resolve(opts.hardhat);
			console.log(`Scanning Hardhat artifacts at ${opts.hardhat}...`);
			const artifacts = scanHardhatArtifacts(opts.hardhat);
			allArtifacts.push(...artifacts);
			for (const a of artifacts) {
				allErrors.push(...a.errors);
			}
			console.log(`  Found ${artifacts.length} contracts with errors`);
		}

		if (allErrors.length === 0) {
			console.error("No custom errors found. Check your artifact paths.");
			process.exit(1);
		}

		const outDir = path.resolve(opts.output);
		fs.mkdirSync(outDir, { recursive: true });

		const hasTypes = !opts.abiOnly;
		const hasAbi = !opts.typesOnly;

		if (hasTypes) {
			const types = generateTypes(allErrors);
			const typesPath = path.join(outDir, "errors.types.ts");
			fs.writeFileSync(typesPath, types, "utf8");
			console.log(`Generated types:    ${typesPath}`);
		}

		if (hasAbi) {
			const registry = generateRegistry(allErrors);
			const registryPath = path.join(outDir, "errors.abi.ts");
			fs.writeFileSync(registryPath, registry, "utf8");
			console.log(`Generated registry: ${registryPath}`);
		}

		let contractNames: string[] = [];
		if (opts.contracts && sourceDir) {
			contractNames = generateContracts(allArtifacts, outDir, sourceDir);
			console.log(`Generated contracts: ${contractNames.join(", ")}`);
		}

		if (opts.contracts || (hasTypes && hasAbi)) {
			const barrel = generateBarrel(outDir, contractNames, hasTypes, hasAbi);
			const barrelPath = path.join(outDir, "index.ts");
			fs.writeFileSync(barrelPath, barrel, "utf8");
			console.log(`Generated barrel:   ${barrelPath}`);
		}

		console.log(`\nTotal unique errors: ${allErrors.length}`);
		console.log("Done!");
	});

program
	.command("generate-short-codes")
	.description(
		"Generate a TypeScript map (SHORT_STRING_ERROR_CODES) from Solidity string constants (library, contract, or file-level)",
	)
	.option(
		"-i, --input <paths>",
		"Solidity file(s): one path, or comma-separated paths to merge (e.g. library + file-level files)",
		"./ProtocolErrorCodes.sol",
	)
	.option(
		"-o, --output <path>",
		"Output path for the generated .ts file",
		"./generated/shortStringCodes.ts",
	)
	.action((opts) => {
		const cwd = process.cwd();
		const inputPaths = opts.input
			.split(",")
			.map((s: string) => s.trim())
			.filter(Boolean);
		try {
			const { count, outputPath } = writeShortStringCodesFromSolidity({
				inputPaths,
				outputPath: opts.output,
				cwd,
				regenerateHint: `npx error-decoder generate-short-codes -i ${opts.input} -o ${opts.output}`,
			});
			console.log(`Wrote ${count} entries → ${outputPath}`);
		} catch (err) {
			console.error(err instanceof Error ? err.message : err);
			process.exit(1);
		}
	});

program
	.command("decode")
	.description("Decode a hex revert string against build artifacts")
	.argument("<data>", "Hex-encoded revert data (0x...)")
	.option("-f, --foundry <path>", "Path to Foundry out/ directory", "./out")
	.option("-h, --hardhat <path>", "Path to Hardhat artifacts/ directory")
	.action(async (data: string, opts) => {
		const { createDecoder } = await import("../index.js");

		const decoder = createDecoder({
			foundryOut: fs.existsSync(path.resolve(opts.foundry))
				? opts.foundry
				: undefined,
			hardhatArtifacts: opts.hardhat,
		});

		console.log(`Registry loaded: ${decoder.registrySize} error selectors\n`);

		const hex = data.startsWith("0x") ? data : `0x${data}`;
		decoder.decodeAndLog(hex as `0x${string}`);
	});

program.parse();
